<?php

namespace App\Listeners\Concerns;

use App\Jobs\DeliverWebhookJob;
use App\Models\Webhook;
use App\Models\WebhookDelivery;
use Illuminate\Support\Str;

trait DispatchesWebhooks
{
    /**
     * Dispatch webhooks for the given event
     */
    protected function dispatchWebhooks(string $eventType, array $payload, ?int $organizationId): void
    {
        if ($organizationId === null) {
            return;
        }

        // Get all active webhooks for this organization
        $webhooks = Webhook::where('organization_id', $organizationId)
            ->where('is_active', true)
            ->get();

        foreach ($webhooks as $webhook) {
            // Check if webhook is subscribed to this event type
            if (! $this->isSubscribedToEvent($webhook, $eventType)) {
                continue;
            }

            // Add unique ID to payload if not present
            if (! isset($payload['id'])) {
                $payload['id'] = 'evt_'.Str::random(32);
            }

            // Create webhook delivery record
            $delivery = WebhookDelivery::create([
                'webhook_id' => $webhook->id,
                'event_type' => $eventType,
                'payload' => $payload,
                'status' => 'pending',
                'signature' => '', // Will be generated by delivery service
            ]);

            // Dispatch the delivery job
            DeliverWebhookJob::dispatch($delivery);
        }
    }

    /**
     * Check if webhook is subscribed to the event type
     */
    protected function isSubscribedToEvent(Webhook $webhook, string $eventType): bool
    {
        $events = $webhook->events ?? [];

        // Check for wildcard subscription
        if (in_array('*', $events)) {
            return true;
        }

        // Check for exact match
        if (in_array($eventType, $events)) {
            return true;
        }

        // Check for pattern match (e.g., "user.*")
        foreach ($events as $subscribedEvent) {
            if (Str::is($subscribedEvent, $eventType)) {
                return true;
            }
        }

        return false;
    }
}
