name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_pgsql, dom, filter, gd, json, bcmath, redis
          coverage: none
          tools: composer:v2

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-interaction --no-scripts

      - name: Run Laravel Pint (Code Style)
        run: ./vendor/bin/pint --test

      - name: Check Composer dependencies security
        run: composer audit --format=plain

  unit-tests:
    name: Unit Tests (PHP ${{ matrix.php }} - ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, ubuntu-24.04 ]
        php: [ '8.3', '8.4' ]
        postgres: [ '15', '16' ]
        exclude:
          - os: ubuntu-22.04
            php: '8.3'
            postgres: '16'
          - os: ubuntu-24.04
            php: '8.4'
            postgres: '15'

    services:
      postgres:
        image: postgres:${{ matrix.postgres }}
        env:
          POSTGRES_USER: authos
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: authos_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, xml, ctype, iconv, intl, pdo_pgsql, dom, filter, gd, json, bcmath, redis
          coverage: xdebug
          tools: composer:v2

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-php${{ matrix.php }}-composer-

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install NPM dependencies
        run: npm ci

      - name: Build frontend assets
        run: npm run build

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan config:clear
          php artisan cache:clear

      - name: Create storage directories
        run: |
          mkdir -p storage/framework/{cache,sessions,testing,views}
          mkdir -p storage/logs
          chmod -R 775 storage bootstrap/cache

      - name: Run database migrations
        env:
          DB_CONNECTION: pgsql
          DB_HOST: localhost
          DB_PORT: 5432
          DB_DATABASE: authos_test
          DB_USERNAME: authos
          DB_PASSWORD: secret
        run: php artisan migrate --force

      - name: Generate Passport keys
        run: php artisan passport:keys --force

      - name: Install Passport clients
        env:
          DB_CONNECTION: pgsql
          DB_HOST: localhost
          DB_PORT: 5432
          DB_DATABASE: authos_test
          DB_USERNAME: authos
          DB_PASSWORD: secret
        run: php artisan passport:install --force

      - name: Run Unit Tests
        env:
          DB_CONNECTION: pgsql
          DB_HOST: localhost
          DB_PORT: 5432
          DB_DATABASE: authos_test
          DB_USERNAME: authos
          DB_PASSWORD: secret
          REDIS_HOST: localhost
          REDIS_PORT: 6379
        run: php artisan test --testsuite=Unit --coverage-clover=coverage.xml

      - name: Upload coverage reports to Codecov
        if: matrix.php == '8.4' && matrix.os == 'ubuntu-24.04' && matrix.postgres == '16'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unit
          name: unit-tests

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-unit-${{ matrix.os }}-php${{ matrix.php }}-pg${{ matrix.postgres }}
          path: |
            storage/logs/
            tests/results/
          retention-days: 7

  integration-tests:
    name: Integration Tests (PHP ${{ matrix.php }})
    runs-on: ubuntu-24.04
    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        php: [ '8.3', '8.4' ]
        postgres: [ '16' ]

    services:
      postgres:
        image: postgres:${{ matrix.postgres }}
        env:
          POSTGRES_USER: authos
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: authos_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, xml, ctype, iconv, intl, pdo_pgsql, dom, filter, gd, json, bcmath, redis
          coverage: xdebug
          tools: composer:v2

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: ${{ runner.os }}-php${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install NPM dependencies
        run: npm ci

      - name: Build frontend assets
        run: npm run build

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan config:clear
          php artisan cache:clear

      - name: Create storage directories
        run: |
          mkdir -p storage/framework/{cache,sessions,testing,views}
          mkdir -p storage/logs
          chmod -R 775 storage bootstrap/cache

      - name: Run database migrations
        env:
          DB_CONNECTION: pgsql
          DB_HOST: localhost
          DB_PORT: 5432
          DB_DATABASE: authos_test
          DB_USERNAME: authos
          DB_PASSWORD: secret
        run: php artisan migrate --force --seed

      - name: Generate Passport keys
        run: php artisan passport:keys --force

      - name: Install Passport clients
        env:
          DB_CONNECTION: pgsql
          DB_HOST: localhost
          DB_PORT: 5432
          DB_DATABASE: authos_test
          DB_USERNAME: authos
          DB_PASSWORD: secret
        run: php artisan passport:install --force

      - name: Run Feature Tests
        env:
          DB_CONNECTION: pgsql
          DB_HOST: localhost
          DB_PORT: 5432
          DB_DATABASE: authos_test
          DB_USERNAME: authos
          DB_PASSWORD: secret
          REDIS_HOST: localhost
          REDIS_PORT: 6379
        run: php artisan test --testsuite=Feature --coverage-clover=coverage.xml

      - name: Upload coverage reports to Codecov
        if: matrix.php == '8.4'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: integration
          name: integration-tests

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-integration-php${{ matrix.php }}
          path: |
            storage/logs/
            tests/results/
          retention-days: 7

  coverage-report:
    name: Code Coverage Report
    needs: [ unit-tests, integration-tests ]
    runs-on: ubuntu-24.04
    if: always()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: test-results-*
          merge-multiple: true

      - name: Comment Coverage on PR
        if: github.event_name == 'pull_request'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  quality-gate:
    name: Quality Gate
    needs: [ code-quality, unit-tests, integration-tests ]
    runs-on: ubuntu-24.04
    if: always()

    steps:
      - name: Check job results
        run: |
          if [ "${{ needs.code-quality.result }}" != "success" ]; then
            echo "Code quality checks failed"
            exit 1
          fi
          if [ "${{ needs.unit-tests.result }}" != "success" ]; then
            echo "Unit tests failed"
            exit 1
          fi
          if [ "${{ needs.integration-tests.result }}" != "success" ]; then
            echo "Integration tests failed"
            exit 1
          fi
          echo "All quality gates passed!"

      - name: Update PR status
        if: github.event_name == 'pull_request'
        run: |
          echo "Quality gate passed - ready for review"
