name: Nightly Comprehensive Tests

on:
  schedule:
    # Run every night at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  full-test-suite:
    name: Full Test Suite (PHP ${{ matrix.php }} - PostgreSQL ${{ matrix.postgres }})
    runs-on: ubuntu-24.04
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        php: [ '8.3', '8.4' ]
        postgres: [ '15', '16' ]

    services:
      postgres:
        image: postgres:${{ matrix.postgres }}
        env:
          POSTGRES_USER: authos
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: authos_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, xml, ctype, iconv, intl, pdo_pgsql, dom, filter, gd, json, bcmath, redis
          coverage: xdebug
          tools: composer:v2

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: ${{ runner.os }}-php${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install NPM dependencies
        run: npm ci

      - name: Build frontend assets
        run: npm run build

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan config:clear
          php artisan cache:clear

      - name: Create storage directories
        run: |
          mkdir -p storage/framework/{cache,sessions,testing,views}
          mkdir -p storage/logs
          chmod -R 775 storage bootstrap/cache

      - name: Setup database
        env:
          DB_CONNECTION: pgsql
          DB_HOST: localhost
          DB_PORT: 5432
          DB_DATABASE: authos_test
          DB_USERNAME: authos
          DB_PASSWORD: secret
        run: |
          php artisan migrate --force --seed
          php artisan passport:keys --force
          php artisan passport:install --force

      - name: Run ALL tests with coverage
        env:
          DB_CONNECTION: pgsql
          DB_HOST: localhost
          DB_PORT: 5432
          DB_DATABASE: authos_test
          DB_USERNAME: authos
          DB_PASSWORD: secret
          REDIS_HOST: localhost
          REDIS_PORT: 6379
        run: php artisan test --coverage-clover=coverage.xml --coverage-html=coverage-html

      - name: Generate coverage report
        run: |
          echo "# Test Coverage Report" > coverage-summary.md
          echo "" >> coverage-summary.md
          echo "PHP ${{ matrix.php }} - PostgreSQL ${{ matrix.postgres }}" >> coverage-summary.md
          echo "" >> coverage-summary.md
          php -r '
            $xml = simplexml_load_file("coverage.xml");
            $metrics = $xml->project->metrics;
            $statements = (float)$metrics["statements"];
            $coveredStatements = (float)$metrics["coveredstatements"];
            $coverage = $statements > 0 ? ($coveredStatements / $statements) * 100 : 0;
            echo "Overall Coverage: " . number_format($coverage, 2) . "%\n";
          ' >> coverage-summary.md

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: nightly-php${{ matrix.php }}-pg${{ matrix.postgres }}
          name: nightly-full-coverage

      - name: Upload coverage artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-php${{ matrix.php }}-pg${{ matrix.postgres }}
          path: |
            coverage.xml
            coverage-html/
            coverage-summary.md
          retention-days: 30

  browser-tests:
    name: Browser Tests (Laravel Dusk)
    runs-on: ubuntu-24.04
    timeout-minutes: 30

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: authos
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: authos_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_pgsql, dom, filter, gd, json, bcmath, redis
          coverage: none
          tools: composer:v2

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install NPM dependencies
        run: npm ci

      - name: Build frontend assets
        run: npm run build

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Setup database
        env:
          DB_CONNECTION: pgsql
          DB_HOST: localhost
          DB_PORT: 5432
          DB_DATABASE: authos_test
          DB_USERNAME: authos
          DB_PASSWORD: secret
        run: |
          php artisan migrate --force --seed
          php artisan passport:keys --force
          php artisan passport:install --force

      - name: Upgrade Chrome Driver
        run: php artisan dusk:chrome-driver --detect

      - name: Start Chrome Driver
        run: ./vendor/laravel/dusk/bin/chromedriver-linux &

      - name: Run Laravel Server
        env:
          DB_CONNECTION: pgsql
          DB_HOST: localhost
          DB_PORT: 5432
          DB_DATABASE: authos_test
          DB_USERNAME: authos
          DB_PASSWORD: secret
        run: php artisan serve --no-reload &

      - name: Wait for server to be ready
        run: |
          timeout 30 bash -c 'until curl -s http://127.0.0.1:8000 > /dev/null; do sleep 1; done'

      - name: Run Dusk Tests
        env:
          DB_CONNECTION: pgsql
          DB_HOST: localhost
          DB_PORT: 5432
          DB_DATABASE: authos_test
          DB_USERNAME: authos
          DB_PASSWORD: secret
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          APP_URL: http://127.0.0.1:8000
        run: php artisan dusk

      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: dusk-screenshots
          path: tests/Browser/screenshots
          retention-days: 7

      - name: Upload Console Logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: dusk-console-logs
          path: tests/Browser/console
          retention-days: 7

  integration-compatibility:
    name: Integration Compatibility Tests
    runs-on: ubuntu-24.04
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        test-group:
          - oauth
          - social-auth
          - sso
          - ldap
          - webhooks
          - bulk-operations

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: authos
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: authos_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_pgsql, dom, filter, gd, json, bcmath, redis, ldap
          coverage: none
          tools: composer:v2

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install NPM dependencies
        run: npm ci

      - name: Build frontend assets
        run: npm run build

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Setup database
        env:
          DB_CONNECTION: pgsql
          DB_HOST: localhost
          DB_PORT: 5432
          DB_DATABASE: authos_test
          DB_USERNAME: authos
          DB_PASSWORD: secret
        run: |
          php artisan migrate --force --seed
          php artisan passport:keys --force
          php artisan passport:install --force

      - name: Run group-specific tests
        env:
          DB_CONNECTION: pgsql
          DB_HOST: localhost
          DB_PORT: 5432
          DB_DATABASE: authos_test
          DB_USERNAME: authos
          DB_PASSWORD: secret
          REDIS_HOST: localhost
          REDIS_PORT: 6379
        run: php artisan test --group=${{ matrix.test-group }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.test-group }}
          path: storage/logs/
          retention-days: 7

  database-migration-tests:
    name: Database Migration Tests
    runs-on: ubuntu-24.04
    timeout-minutes: 20

    strategy:
      matrix:
        postgres: [ '15', '16' ]
        migration-type: [ 'fresh', 'rollback', 'refresh' ]

    services:
      postgres:
        image: postgres:${{ matrix.postgres }}
        env:
          POSTGRES_USER: authos
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: authos_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_pgsql
          coverage: none
          tools: composer:v2

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-interaction --no-scripts

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Test fresh migration
        if: matrix.migration-type == 'fresh'
        env:
          DB_CONNECTION: pgsql
          DB_HOST: localhost
          DB_PORT: 5432
          DB_DATABASE: authos_test
          DB_USERNAME: authos
          DB_PASSWORD: secret
        run: php artisan migrate:fresh --force --seed

      - name: Test rollback migration
        if: matrix.migration-type == 'rollback'
        env:
          DB_CONNECTION: pgsql
          DB_HOST: localhost
          DB_PORT: 5432
          DB_DATABASE: authos_test
          DB_USERNAME: authos
          DB_PASSWORD: secret
        run: |
          php artisan migrate --force
          php artisan migrate:rollback --force
          php artisan migrate --force

      - name: Test refresh migration
        if: matrix.migration-type == 'refresh'
        env:
          DB_CONNECTION: pgsql
          DB_HOST: localhost
          DB_PORT: 5432
          DB_DATABASE: authos_test
          DB_USERNAME: authos
          DB_PASSWORD: secret
        run: php artisan migrate:refresh --force --seed

      - name: Verify database schema
        env:
          DB_CONNECTION: pgsql
          DB_HOST: localhost
          DB_PORT: 5432
          DB_DATABASE: authos_test
          DB_USERNAME: authos
          DB_PASSWORD: secret
        run: |
          php artisan tinker --execute="
            \$tables = DB::select('SELECT table_name FROM information_schema.tables WHERE table_schema = \'public\' ORDER BY table_name');
            echo 'Total tables: ' . count(\$tables) . PHP_EOL;
            foreach (\$tables as \$table) {
              echo \$table->table_name . PHP_EOL;
            }
          "

  nightly-summary:
    name: Nightly Test Summary
    needs: [ full-test-suite, browser-tests, integration-compatibility, database-migration-tests ]
    runs-on: ubuntu-24.04
    if: always()

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Generate Summary Report
        run: |
          echo "# Nightly Test Summary - $(date -u)" > summary.md
          echo "" >> summary.md
          echo "## Test Results" >> summary.md
          echo "" >> summary.md
          echo "| Job | Status |" >> summary.md
          echo "|-----|--------|" >> summary.md
          echo "| Full Test Suite | ${{ needs.full-test-suite.result }} |" >> summary.md
          echo "| Browser Tests | ${{ needs.browser-tests.result }} |" >> summary.md
          echo "| Integration Compatibility | ${{ needs.integration-compatibility.result }} |" >> summary.md
          echo "| Database Migrations | ${{ needs.database-migration-tests.result }} |" >> summary.md
          echo "" >> summary.md

          # Check for failures
          if [ "${{ needs.full-test-suite.result }}" == "failure" ] || \
             [ "${{ needs.browser-tests.result }}" == "failure" ] || \
             [ "${{ needs.integration-compatibility.result }}" == "failure" ] || \
             [ "${{ needs.database-migration-tests.result }}" == "failure" ]; then
            echo "## ⚠️ FAILURES DETECTED" >> summary.md
            echo "" >> summary.md
            echo "One or more test suites have failed. Please investigate." >> summary.md
          else
            echo "## ✅ ALL TESTS PASSED" >> summary.md
          fi

      - name: Upload summary
        uses: actions/upload-artifact@v4
        with:
          name: nightly-summary
          path: summary.md
          retention-days: 90

      - name: Create issue on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const summary = fs.readFileSync('summary.md', 'utf8');

            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Nightly Tests Failed - ${new Date().toISOString().split('T')[0]}`,
              body: summary,
              labels: ['automated', 'test-failure', 'priority:high']
            });

      - name: Send Slack notification on failure
        if: failure() && secrets.SLACK_WEBHOOK
        run: |
          curl -X POST ${{ secrets.SLACK_WEBHOOK }} \
            -H 'Content-Type: application/json' \
            -d '{
              "text": "❌ Nightly tests failed for AuthOS",
              "attachments": [{
                "color": "danger",
                "fields": [{
                  "title": "Date",
                  "value": "'"$(date -u)"'",
                  "short": true
                }, {
                  "title": "Workflow",
                  "value": "${{ github.workflow }}",
                  "short": true
                }]
              }]
            }'
