<?php

namespace App\Filament\Resources\ComplianceReportResource\Pages;

use App\Filament\Resources\ComplianceReportResource;
use App\Models\ComplianceReport;
use Filament\Actions\Action;
use Filament\Infolists\Components\KeyValueEntry;
use Filament\Infolists\Components\TextEntry;
use Filament\Resources\Pages\ViewRecord;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;

class ViewComplianceReport extends ViewRecord
{
    protected static string $resource = ComplianceReportResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Action::make('download_pdf')
                ->label('Download PDF')
                ->icon('heroicon-o-arrow-down-tray')
                ->color('success')
                ->visible(fn (ComplianceReport $record): bool => $record->isCompleted()
                    && ! empty($record->file_path_pdf)
                    && ! $record->isExpired())
                ->action(fn (ComplianceReport $record) => ComplianceReportResource::streamReportFile($record, 'pdf')),

            Action::make('download_json')
                ->label('Download JSON')
                ->icon('heroicon-o-code-bracket')
                ->color('gray')
                ->visible(fn (ComplianceReport $record): bool => $record->isCompleted()
                    && ! empty($record->file_path_json)
                    && ! $record->isExpired())
                ->action(fn (ComplianceReport $record) => ComplianceReportResource::streamReportFile($record, 'json')),
        ];
    }

    public function infolist(Schema $schema): Schema
    {
        return $schema->schema([
            Section::make('Report Details')
                ->schema([
                    TextEntry::make('id')->label('Report ID'),

                    TextEntry::make('report_type')
                        ->label('Type')
                        ->badge()
                        ->formatStateUsing(fn (string $state): string => match ($state) {
                            ComplianceReport::TYPE_SOC2 => 'SOC 2',
                            ComplianceReport::TYPE_ISO27001 => 'ISO 27001',
                            ComplianceReport::TYPE_GDPR => 'GDPR',
                            default => $state,
                        }),

                    TextEntry::make('status')
                        ->badge()
                        ->color(fn (string $state): string => match ($state) {
                            ComplianceReport::STATUS_GENERATING => 'warning',
                            ComplianceReport::STATUS_COMPLETED => 'success',
                            ComplianceReport::STATUS_FAILED => 'danger',
                            default => 'gray',
                        }),

                    TextEntry::make('organization.name')
                        ->label('Organization')
                        ->badge(),

                    TextEntry::make('generatedBy.name')
                        ->label('Generated By')
                        ->placeholder('System / Scheduled'),

                    TextEntry::make('schedule.id')
                        ->label('Scheduled Report')
                        ->placeholder('On-demand')
                        ->prefix('#'),

                    TextEntry::make('period_start')
                        ->label('Period Start')
                        ->date(),

                    TextEntry::make('period_end')
                        ->label('Period End')
                        ->date(),

                    TextEntry::make('generated_at')
                        ->label('Generated At')
                        ->dateTime()
                        ->placeholder('Pending'),

                    TextEntry::make('expires_at')
                        ->label('Expires At')
                        ->dateTime()
                        ->color(fn (ComplianceReport $record): string => $record->isExpired() ? 'danger' : 'gray')
                        ->placeholder('No expiry'),
                ])
                ->columns(2)
                ->columnSpanFull(),

            Section::make('Top-line Metrics')
                ->schema([
                    KeyValueEntry::make('summary')
                        ->keyLabel('Metric')
                        ->valueLabel('Value')
                        ->columnSpanFull(),
                ])
                ->collapsible()
                ->visible(fn (ComplianceReport $record): bool => ! empty($record->summary))
                ->columnSpanFull(),

            Section::make('Files')
                ->schema([
                    TextEntry::make('file_path_pdf')
                        ->label('PDF Path')
                        ->placeholder('Not generated'),

                    TextEntry::make('file_path_json')
                        ->label('JSON Path')
                        ->placeholder('Not generated'),
                ])
                ->columns(2)
                ->collapsible()
                ->columnSpanFull(),

            Section::make('Error')
                ->schema([
                    TextEntry::make('error_message')
                        ->label('Error Message')
                        ->columnSpanFull()
                        ->placeholder('No errors'),
                ])
                ->collapsible()
                ->collapsed()
                ->visible(fn (ComplianceReport $record): bool => $record->status === ComplianceReport::STATUS_FAILED
                    || ! empty($record->error_message))
                ->columnSpanFull(),
        ]);
    }
}
