<?php

namespace App\Listeners;

use App\Events\ApplicationCreatedEvent;
use App\Events\AuthFailedEvent;
use App\Events\AuthLoginEvent;
use App\Events\MfaEnabledEvent;
use App\Events\OrganizationUpdatedEvent;
use App\Events\UserCreatedEvent;
use App\Events\UserDeletedEvent;
use App\Events\UserUpdatedEvent;
use App\Jobs\DeliverWebhookJob;
use App\Models\Webhook;
use App\Models\WebhookDelivery;
use Illuminate\Support\Str;

class WebhookEventSubscriber
{
    /**
     * Handle user created event
     */
    public function handleUserCreated(UserCreatedEvent $event): void
    {
        $this->dispatchWebhooks($event->getEventType(), $event->getPayload(), $event->user->organization_id);
    }

    /**
     * Handle user updated event
     */
    public function handleUserUpdated(UserUpdatedEvent $event): void
    {
        $this->dispatchWebhooks($event->getEventType(), $event->getPayload(), $event->user->organization_id);
    }

    /**
     * Handle user deleted event
     */
    public function handleUserDeleted(UserDeletedEvent $event): void
    {
        $this->dispatchWebhooks($event->getEventType(), $event->getPayload(), $event->user->organization_id);
    }

    /**
     * Handle auth login event
     */
    public function handleAuthLogin(AuthLoginEvent $event): void
    {
        $this->dispatchWebhooks($event->getEventType(), $event->getPayload(), $event->user->organization_id);
    }

    /**
     * Handle auth failed event
     */
    public function handleAuthFailed(AuthFailedEvent $event): void
    {
        // Auth failed events might not have organization context
        $this->dispatchWebhooks($event->getEventType(), $event->getPayload(), $event->organizationId ?? null);
    }

    /**
     * Handle MFA enabled event
     */
    public function handleMfaEnabled(MfaEnabledEvent $event): void
    {
        $this->dispatchWebhooks($event->getEventType(), $event->getPayload(), $event->user->organization_id);
    }

    /**
     * Handle application created event
     */
    public function handleApplicationCreated(ApplicationCreatedEvent $event): void
    {
        $this->dispatchWebhooks($event->getEventType(), $event->getPayload(), $event->application->organization_id);
    }

    /**
     * Handle organization updated event
     */
    public function handleOrganizationUpdated(OrganizationUpdatedEvent $event): void
    {
        $this->dispatchWebhooks($event->getEventType(), $event->getPayload(), $event->organization->id);
    }

    /**
     * Track processed events to prevent duplicate dispatches
     */
    private static $processedEvents = [];

    /**
     * Dispatch webhooks for the given event
     */
    protected function dispatchWebhooks(string $eventType, array $payload, ?int $organizationId): void
    {
        if ($organizationId === null) {
            return;
        }

        // Generate a unique key for this event to prevent duplicate processing
        $eventKey = md5($eventType.'|'.$organizationId.'|'.json_encode($payload));

        // Skip if we've already processed this exact event in this request
        if (isset(self::$processedEvents[$eventKey])) {
            return;
        }

        // Mark as processed
        self::$processedEvents[$eventKey] = true;

        // Get all active webhooks for this organization
        $webhooks = Webhook::where('organization_id', $organizationId)
            ->where('is_active', true)
            ->get();

        foreach ($webhooks as $webhook) {
            // Check if webhook is subscribed to this event type
            if (! $this->isSubscribedToEvent($webhook, $eventType)) {
                continue;
            }

            // Add unique ID to payload if not present
            if (! isset($payload['id'])) {
                $payload['id'] = 'evt_'.Str::random(32);
            }

            // Create webhook delivery record
            $delivery = WebhookDelivery::create([
                'webhook_id' => $webhook->id,
                'event_type' => $eventType,
                'payload' => $payload,
                'status' => 'pending',
                'signature' => '', // Will be generated by delivery service
            ]);

            // Dispatch the delivery job
            DeliverWebhookJob::dispatch($delivery);
        }
    }

    /**
     * Check if webhook is subscribed to the event type
     */
    protected function isSubscribedToEvent(Webhook $webhook, string $eventType): bool
    {
        $events = $webhook->events ?? [];

        // Check for wildcard subscription
        if (in_array('*', $events)) {
            return true;
        }

        // Check for exact match
        if (in_array($eventType, $events)) {
            return true;
        }

        // Check for pattern match (e.g., "user.*")
        foreach ($events as $subscribedEvent) {
            if (Str::is($subscribedEvent, $eventType)) {
                return true;
            }
        }

        return false;
    }
}
