<?php

namespace App\Filament\Resources;

use App\Filament\Resources\ComplianceReportResource\Pages\ListComplianceReports;
use App\Filament\Resources\ComplianceReportResource\Pages\ViewComplianceReport;
use App\Models\ComplianceReport;
use App\Models\Organization;
use App\Models\User;
use BackedEnum;
use Filament\Actions\Action;
use Filament\Actions\DeleteAction;
use Filament\Actions\ViewAction;
use Filament\Facades\Filament;
use Filament\Forms\Components\DatePicker;
use Filament\Resources\Resource;
use Filament\Schemas\Schema;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Filters\Filter;
use Filament\Tables\Filters\SelectFilter;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\Storage;
use Symfony\Component\HttpFoundation\StreamedResponse;
use UnitEnum;

class ComplianceReportResource extends Resource
{
    protected static ?string $model = ComplianceReport::class;

    protected static string|BackedEnum|null $navigationIcon = null;

    protected static string|UnitEnum|null $navigationGroup = 'Enterprise';

    protected static ?int $navigationSort = 5;

    protected static ?string $navigationLabel = 'Compliance Reports';

    protected static ?string $modelLabel = 'Compliance Report';

    protected static ?string $pluralModelLabel = 'Compliance Reports';

    public static function canCreate(): bool
    {
        return false;
    }

    public static function form(Schema $schema): Schema
    {
        return $schema->schema([]);
    }

    public static function table(Table $table): Table
    {
        /** @var User|null $currentUser */
        $currentUser = Filament::auth()->user();
        $isSuperAdmin = $currentUser && $currentUser->isSuperAdmin();

        return $table->columns([
            TextColumn::make('id')
                ->label('ID')
                ->sortable(),

            TextColumn::make('report_type')
                ->label('Type')
                ->badge()
                ->formatStateUsing(fn (string $state): string => match ($state) {
                    ComplianceReport::TYPE_SOC2 => 'SOC 2',
                    ComplianceReport::TYPE_ISO27001 => 'ISO 27001',
                    ComplianceReport::TYPE_GDPR => 'GDPR',
                    default => $state,
                })
                ->color(fn (string $state): string => match ($state) {
                    ComplianceReport::TYPE_SOC2 => 'info',
                    ComplianceReport::TYPE_ISO27001 => 'warning',
                    ComplianceReport::TYPE_GDPR => 'success',
                    default => 'gray',
                })
                ->searchable()
                ->sortable(),

            TextColumn::make('status')
                ->badge()
                ->color(fn (string $state): string => match ($state) {
                    ComplianceReport::STATUS_GENERATING => 'warning',
                    ComplianceReport::STATUS_COMPLETED => 'success',
                    ComplianceReport::STATUS_FAILED => 'danger',
                    default => 'gray',
                })
                ->sortable(),

            TextColumn::make('organization.name')
                ->badge()
                ->searchable()
                ->sortable()
                ->visible($isSuperAdmin),

            TextColumn::make('generatedBy.name')
                ->label('Generated By')
                ->placeholder('System')
                ->searchable()
                ->sortable(),

            TextColumn::make('period_start')
                ->label('Period')
                ->formatStateUsing(fn ($state, ComplianceReport $record): string => $state
                    ? $record->period_start->toDateString().' → '.$record->period_end?->toDateString()
                    : '—')
                ->sortable(),

            TextColumn::make('generated_at')
                ->dateTime()
                ->sortable(),

            TextColumn::make('expires_at')
                ->dateTime()
                ->sortable()
                ->color(fn (ComplianceReport $record): string => $record->isExpired() ? 'danger' : 'gray'),

            TextColumn::make('created_at')
                ->dateTime()
                ->sortable()
                ->toggleable(isToggledHiddenByDefault: true),
        ])->filters([
            SelectFilter::make('report_type')
                ->options([
                    ComplianceReport::TYPE_SOC2 => 'SOC 2',
                    ComplianceReport::TYPE_ISO27001 => 'ISO 27001',
                    ComplianceReport::TYPE_GDPR => 'GDPR',
                ]),

            SelectFilter::make('status')
                ->options([
                    ComplianceReport::STATUS_GENERATING => 'Generating',
                    ComplianceReport::STATUS_COMPLETED => 'Completed',
                    ComplianceReport::STATUS_FAILED => 'Failed',
                ]),

            SelectFilter::make('organization_id')
                ->label('Organization')
                ->options(fn () => Organization::pluck('name', 'id')->toArray())
                ->visible($isSuperAdmin),

            Filter::make('generated_at')
                ->schema([
                    DatePicker::make('from')->label('Generated from'),
                    DatePicker::make('to')->label('Generated to'),
                ])
                ->query(function (Builder $query, array $data): Builder {
                    return $query
                        ->when($data['from'] ?? null, fn (Builder $q, $date) => $q->whereDate('generated_at', '>=', $date))
                        ->when($data['to'] ?? null, fn (Builder $q, $date) => $q->whereDate('generated_at', '<=', $date));
                }),
        ])->recordActions([
            ViewAction::make(),

            Action::make('download_pdf')
                ->label('PDF')
                ->icon('heroicon-o-arrow-down-tray')
                ->color('success')
                ->visible(fn (ComplianceReport $record): bool => $record->isCompleted()
                    && ! empty($record->file_path_pdf)
                    && ! $record->isExpired())
                ->action(fn (ComplianceReport $record) => static::streamReportFile($record, 'pdf')),

            Action::make('download_json')
                ->label('JSON')
                ->icon('heroicon-o-code-bracket')
                ->color('gray')
                ->visible(fn (ComplianceReport $record): bool => $record->isCompleted()
                    && ! empty($record->file_path_json)
                    && ! $record->isExpired())
                ->action(fn (ComplianceReport $record) => static::streamReportFile($record, 'json')),

            DeleteAction::make()
                ->before(function (ComplianceReport $record): void {
                    $disk = Storage::disk('local');
                    if ($record->file_path_pdf && $disk->exists($record->file_path_pdf)) {
                        $disk->delete($record->file_path_pdf);
                    }
                    if ($record->file_path_json && $disk->exists($record->file_path_json)) {
                        $disk->delete($record->file_path_json);
                    }
                }),
        ])->defaultSort('created_at', 'desc')->striped();
    }

    public static function streamReportFile(ComplianceReport $report, string $format): StreamedResponse
    {
        $path = match ($format) {
            'pdf' => $report->file_path_pdf,
            'json' => $report->file_path_json,
            default => abort(400, 'Invalid format'),
        };

        $disk = Storage::disk('local');
        abort_unless($path && $disk->exists($path), 404, 'Report file not found');

        $contentType = $format === 'pdf' ? 'application/pdf' : 'application/json';

        return response()->streamDownload(
            fn () => print $disk->get($path),
            basename($path),
            ['Content-Type' => $contentType],
        );
    }

    public static function getPages(): array
    {
        return [
            'index' => ListComplianceReports::route('/'),
            'view' => ViewComplianceReport::route('/{record}'),
        ];
    }

    public static function getNavigationBadge(): ?string
    {
        $count = static::getEloquentQuery()
            ->where('status', ComplianceReport::STATUS_COMPLETED)
            ->whereDate('generated_at', today())
            ->count();

        return $count > 0 ? (string) $count : null;
    }

    public static function getNavigationBadgeColor(): string|array|null
    {
        return 'success';
    }

    public static function getEloquentQuery(): Builder
    {
        $query = parent::getEloquentQuery()->with(['organization', 'generatedBy']);

        /** @var User|null $user */
        $user = Filament::auth()->user();

        if ($user && $user->isSuperAdmin()) {
            return $query;
        }

        if ($user && $user->organization_id) {
            $query->where('organization_id', $user->organization_id);
        }

        return $query;
    }
}
